### Multiple matrics

In [7]:
import numpy as np

m1 = np.array([[1,2,3]]).reshape(-1,1)
m2 = np.array([[1,2,3],[4,5,6]])
np.matmul(m2, m1) # 1*1+2*2+3*3 and 4*1+5*2+6*3
# array([[14],
#        [32]])

array([[14],
       [32]])

In [8]:
# Similar function
m1 = np.array([[1,2,3]]).reshape(-1,1)
m2 = np.array([[1,2,3],[4,5,6]])
np.dot(m2,m1)
# array([[14],
#        [32]])

array([[14],
       [32]])

### Transpose matrices

In [11]:
m1 = np.array([[1,2,3],[4,5,6]])
m1.transpose()
#or
m1.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### Other functions

In [14]:
ary = np.array([1, 1, 2, 3, 1, 5])
np.unique(ary) # array([1, 2, 3, 5])

array([1, 2, 3, 5])

### Intersection 

In [17]:
ary1 = np.array([1, 2, 3])
ary2 = np.array([3, 4, 5, 6])
np.intersect1d(ary1, ary2, assume_unique=True) # assume_unique - ускоряет опярацию,т.к. не учитывает повторяющиеся элементы


array([3])

### Serialize arrays

### Save

In [27]:
ary1 = np.array([1,2,3])
np.save('ary-data.npy', ary1)
np.load('ary-data.npy')

array([1, 2, 3])

### Savez (save multiple arrays at once)

In [42]:
np.savez('ary-data.npz', ary1, np.array([3,4,5]))
d = np.load('ary-data.npz')
d.keys()
d['arr_0'], d['arr_1']

(array([1, 2, 3]), array([3, 4, 5]))

In [44]:
kwargs = {'ary1': np.array([1,2,3]), 'ary2':np.array([4,5,6])}
np.savez('ary-data.npz', **kwargs)
d = np.load('ary-data.npz')
d['ary1'], d['ary2']

(array([1, 2, 3]), array([4, 5, 6]))